name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variants:
          - tag: ""
            label: "Default"
          - tag: "-fips"
            patches: fips.patch
            label: "FIPS"
            build_args: |
              BUILD_IMAGE=ghcr.io/goauthentik/fips-debian:trixie-slim-fips
    name: Build ${{ matrix.variants.label }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - id: tag
        run: |
          owner="${{ github.repository_owner }}"
          echo "org=$(echo $owner | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      - name: Apply patches
        run: |
          git apply ${{ matrix.variants.patches }} --allow-empty
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.tag.outputs.org }}/guacd
          flavor: |
            latest=auto
            suffix=${{ matrix.variants.tag }}
      - id: build
        uses: docker/build-push-action@v6.18.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: ${{ matrix.variants.build_args }}
          file: Dockerfile.debian
          provenance: mode=max
          sbom: true
          cache-from: type=registry,ref=ghcr.io/{{ steps.tag.outputs.org }}/guacd:buildcache${{ matrix.variants.tag }}
          cache-to: type=registry,ref=ghcr.io/{{ steps.tag.outputs.org }}/guacd:buildcache${{ matrix.variants.tag }},mode=max
      - uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ steps.tag.outputs.org }}/guacd
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: ${{ github.event_name != 'pull_request' }}
